---
abstract: 'Perl extension to get info from MP4 files.'
author:
  - 'Simon Wistow, E<lt>simon@thegestalt.orgE<gt>'
build_requires:
  Module::Build: 0.38
  YAML: 0
configure_requires:
  Module::Build: 0.38
  YAML: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AudioFile-Info-MP4-Info
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
    version: 0
  AudioFile::Info::MP4::Info:
    file: lib/AudioFile/Info/MP4/Info.pm
    version: 0.6
requires:
  AudioFile::Info: 0
  MP4::Info: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.6
